repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: templates/infrastructure/awsmanaged/cloudformation.*.yaml
      - id: check-added-large-files

  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-lint
      - id: go-unit-tests
