on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]

jobs:
  ci:
    name: test and build source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pre-commit
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run pre-commit hooks
        run: |
          python -m pip install pre-commit
          make precommit

      - name: Test
        run: make test

      - name: Build
        run: make build
